apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medicServer-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Bibi1989/medic-server-argocd-config.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: medicServer

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true