apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicclient-deployment
spec:
  selector:
    matchLabels:
      app: medicclient
  replicas: 1
  template:
    metadata:
      labels:
        app: medicclient
    spec:
      containers:
        - name: medicclient
          image: bibi1989/medic-client:v1
          ports:
            - containerPort: 3005
