apiVersion: v1
kind: Service
metadata:
  name: medicclient-service
spec:
  type: NodePort
  selector:
    app: medicclient
  ports:
    - port: 3021
      protocol: TCP
      targetPort: 3021
      nodePort: 30351
