apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicserver-deployment
spec:
  selector:
    matchLabels:
      app: medicserver
  replicas: 1
  template:
    metadata:
      labels:
        app: medicserver
    spec:
      containers:
        - name: medicserver
          image: bibi1989/medic-server:v1.0
          ports:
            - containerPort: 3005
